Usecase/email regex
monkeypatch/monkeypatch.py pull request #65
Opened 2023-11-13 14:17 UTC by bmagz

This example replaces regex for matching an email to a list of names. Example use case is where a company has an email list of thousands of emails and list of names in their database that aren't mapped.

2023-11-14 05:45 UTC, bmagz commented on examples/email_matching/main.py
> +    assert match_email("jsmith@gmail.com", ["John Smith", "Jen Smith"]) == ""
Absolutely

2023-11-15 09:05 UTC, JackHopkins requested changes

2023-11-15 09:05 UTC, JackHopkins commented on examples/email_matching/test_email_matching.py
> +    assert match_email("sarah@test.com", NAMES) == ""
Shouldn't this look like:
```
assert not match_email("davis@example.com", NAMES)
```
or
```
assert match_email("davis@example.com", NAMES) == None
```
?

2023-11-16 20:59 UTC, MartBakler approved these changes

2023-11-19 00:33 UTC, JackHopkins approved these changes

2023-11-19 00:34 UTC, merged